.TH unity-tweak-tool "1" "11 February 2013" "" "Unity User's Manual"

.SH NAME
unity-tweak-tool \- configuration manager for Unity desktop environment

.SH SYNOPSIS
.B unity-tweak-tool
.RI [ options ]
.br

.SH DESCRIPTION
The \fBunity-tweak-tool\fP program can be used to tweak Unity desktop environment. Unity Tweak Tool is a one-stop settings manager for Ubuntu Unity.

.SH OPTIONS
.IP \fB\-u\fP
Starts \fBunity-tweak-tool\fP in Unity section.

.IP \fB\-w\fP
Starts \fBunity-tweak-tool\fP in Window Manager section.

.IP \fB\-a\fP
Starts \fBunity-tweak-tool\fP in Appearance section.

.IP \fB\-s\fP
Starts \fBunity-tweak-tool\fP in System section.

.IP \fB\--reset-unity\fP
Reset Unity, wiping all changes to configuration.

.SH BUGS
Please report any bug you may experience to the \fBunity-tweak-tool\fP developers, who can
be reached at \fRhttps://launchpad.net/unity-tweak-tool\fP.

.SH AUTHOR
\fBunity-tweak-tool\fR was written by Freyja Development Team and this manual page by Barneedhar Vigneshwar <barneedhar@ubuntu.com>.

Both are released under the GNU General Public License, version 3 or later.
