#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Team:
#   J Phani Mahesh <phanimahesh@gmail.com>
#   Barneedhar (jokerdino) <barneedhar@ubuntu.com>
#   Amith KK <amithkumaran@gmail.com>
#   Georgi Karavasilev <motorslav@gmail.com>
#   Sam Tran <samvtran@gmail.com>
#   Sam Hewitt <hewittsamuel@gmail.com>
#   Angel Araya <al.arayaq@gmail.com>
#
# Description:
#   A One-stop configuration tool for Unity.
#
# Legal Stuff:
#
# This file is a part of Unity Tweak Tool
#
# Unity Tweak Tool is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# Unity Tweak Tool is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

import argparse
import UnityTweakTool

parser = argparse.ArgumentParser()
optgrp = parser.add_mutually_exclusive_group()

optgrp.add_argument('-u', '--unity', help='Start in the Unity tab', action='store_true')
optgrp.add_argument('-w', '--winmng', help='Start in the WindowManager tab', action='store_true')
optgrp.add_argument('-a', '--appearance', help='Start in the appearance tab', action='store_true')
optgrp.add_argument('-s', '--system', help='Start in the system tab', action='store_true')
optgrp.add_argument('-r', '--restore', help='Restore settings to its default values', action='store_true')

args=parser.parse_args()

if args.unity:
    UnityTweakTool.init(1)
elif args.winmng:
    UnityTweakTool.init(2)
elif args.appearance:
    UnityTweakTool.init(3)
elif args.system:
    UnityTweakTool.init(4)
elif args.restore:
    UnityTweakTool.reset_all()
else:
    UnityTweakTool.init()
